name: 🚀 Deploy to ByetHost via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📂 Deploy to ByetHost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftpupload.net
          username: b12_38966702
          password: 1007745160Yy.
          local-dir: ./PERSONAL-PORTFOLIO
